# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_bh_models.ipynb.

# %% ../../nbs/03_bh_models.ipynb #nbdev-31acf7
from __future__ import annotations

import numpy as np
from scipy.optimize import curve_fit

# %% auto #0
__all__ = ['linear_region', 'frolich', 'fit_frolich']

# %% ../../nbs/03_bh_models.ipynb #1c315d2d
def linear_region(H: np.ndarray, mu_r: float) -> np.ndarray:
    r"""
    Linear BH approximation: B = μ₀ · μr · H
    
    Valid for low flux densities well below saturation.
    
    Args:
        H: Magnetic field intensity (A/m)
        mu_r: Relative permeability
    
    Returns:
        Flux density B (T)
    """
    MU_0 = 4 * np.pi * 1e-7
    return MU_0 * mu_r * np.asarray(H, dtype=float)

# %% ../../nbs/03_bh_models.ipynb #8b480f97
def frolich(H: np.ndarray, a: float, b: float) -> np.ndarray:
    r"""
    Fröhlich-Kennelly analytical BH approximation.
    
    B = H / (a + b * |H|)
    
    Args:
        H: Magnetic field intensity (A/m)
        a: Model parameter (dimensionless)
        b: Model parameter (m/A)
    
    Returns:
        Flux density B (T)
    """
    H = np.asarray(H, dtype=float)
    return H / (a + b * np.abs(H))

# %% ../../nbs/03_bh_models.ipynb #9d058944
def fit_frolich(H: np.ndarray, B: np.ndarray) -> tuple[float, float]:
    """
    Fit Fröhlich model parameters (a, b) to measured BH data.
    
    Args:
        H: Measured field intensity (A/m)
        B: Measured flux density (T)
    
    Returns:
        Tuple (a, b) of fitted parameters
    """
    H = np.asarray(H, dtype=float)
    B = np.asarray(B, dtype=float)
    (a, b), _ = curve_fit(frolich, H, B, p0=[1.0, 1.0], maxfev=5000)
    return float(a), float(b)
