# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/magnetics/02_electrical_steel.ipynb.

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #nbdev-995105
from __future__ import annotations

import functools
import os
import pickle
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

# %% auto #0
__all__ = ['SAMPLE_BH', 'SAMPLE_LOSS', 'SteelGrade', 'SteelDatabase', 'load_literature_database', 'get_steel_library']

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #e70d1604
@dataclass
class SteelGrade:
    """Container for electrical steel grade properties."""
    name:         str
    manufacturer: str
    bh_data:      pd.DataFrame = field(default_factory=pd.DataFrame)
    loss_data:    pd.DataFrame = field(default_factory=pd.DataFrame)
    source_file:  str = ""
    
    @property
    def frequencies(self) -> list[float]:
        """Available frequencies in loss dataset (Hz)."""
        if self.loss_data.empty or "frequency [Hz]" not in self.loss_data.columns:
            return []
        return sorted(self.loss_data["frequency [Hz]"].unique().tolist())
    
    @property
    def bh_points(self) -> int:
        """Number of B-H data points."""
        return len(self.bh_data)
    
    def loss_at(self, freq: float, B: float) -> float:
        """Interpolate core loss at given frequency and flux density."""
        if freq not in self.frequencies:
            raise ValueError(f"Frequency {freq} Hz not available")
        b_col = next((c for c in ("B [T]", "J [T]") if c in self.loss_data.columns), None)
        loss_col = next((c for c in ("core loss P [W/kg]", "Core Loss [W/kg]") 
                         if c in self.loss_data.columns), None)
        if not b_col or not loss_col:
            raise ValueError("Loss data missing expected columns.")
        subset = self.loss_data[self.loss_data["frequency [Hz]"] == freq].sort_values(b_col)
        return float(np.interp(B, subset[b_col].values, subset[loss_col].values))

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #d4e5f6a7
class SteelDatabase:
    """
    Unified loader for electrical steel manufacturer data.

    Supports Voestalpine (isovac), ThyssenKrupp (PowerCore), and SURA grades.
    Data is loaded from pickle caches on first access and cached in memory.

    Args:
        data_dir: Path to the datasheets root directory.
    """
    _CACHE_SUBDIR = 'steel_data_cache'
    _VOEST_SUBDIR = 'Voelstapine Electrical Steel'

    def __init__(self, data_dir: str) -> None:
        self._data_dir = Path(data_dir)
        self._cache_dir = self._data_dir / self._CACHE_SUBDIR
        self._voest_dir = self._data_dir / self._VOEST_SUBDIR
        self._index: dict[str, tuple[str, str]] | None = None

    def _build_index(self) -> dict[str, tuple[str, str]]:
        index: dict[str, tuple[str, str]] = {}
        if self._voest_dir.exists():
            for f in os.listdir(self._voest_dir):
                if f.endswith('.xlsx') and f.startswith('Simulation-data-isovac'):
                    parts = f.replace('Simulation-data-', '').replace('-voestalpine', '').split('-')
                    if len(parts) >= 2:
                        grade = f'ISOVAC{parts[0]} {parts[1]}'
                        index[grade] = ('voestalpine', str(self._voest_dir / f))
        if self._cache_dir.exists():
            for f in os.listdir(self._cache_dir):
                if not f.endswith('.pkl'):
                    continue
                pkl_path = str(self._cache_dir / f)
                try:
                    with open(pkl_path, 'rb') as fh:
                        data = pickle.load(fh)
                    grade = data.get('grade')
                    if not grade:
                        continue
                    if 'powercore' in f.lower():
                        index[grade] = ('thyssenkrupp', pkl_path)
                    elif f.lower().startswith('sura_'):
                        index[grade] = ('sura', pkl_path)
                except Exception:
                    pass
        return index

    @property
    def index(self) -> dict[str, tuple[str, str]]:
        if self._index is None:
            self._index = self._build_index()
        return self._index

    @property
    def grades(self) -> list[str]:
        return sorted(self.index.keys())

    @property
    def manufacturers(self) -> dict[str, list[str]]:
        result: dict[str, list[str]] = {}
        for grade, (mfr, _) in self.index.items():
            result.setdefault(mfr, []).append(grade)
        return {k: sorted(v) for k, v in result.items()}

    @functools.lru_cache(maxsize=64)
    def load(self, grade: str) -> 'SteelGrade':
        """Load a grade by name. Cached in memory."""
        if grade not in self.index:
            raise KeyError(f"Grade '{grade}' not found. Available: {self.grades}")
        mfr, path = self.index[grade]
        bh_df, loss_df = self._load_file(path)
        return SteelGrade(name=grade, manufacturer=mfr, bh_data=bh_df, loss_data=loss_df, source_file=path)

    def _load_file(self, path: str) -> tuple[pd.DataFrame, pd.DataFrame]:
        p = Path(path)
        if p.suffix == '.pkl':
            return self._from_pickle(p)
        cache_path = self._cache_dir / (p.stem + '.pkl')
        if cache_path.exists():
            return self._from_pickle(cache_path)
        return self._from_excel(p)

    @staticmethod
    def _from_pickle(path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
        with open(path, 'rb') as f:
            d = pickle.load(f)
        return d.get('bh_data', pd.DataFrame()), d.get('loss_data', pd.DataFrame())

    @staticmethod
    def _from_excel(path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
        mu0 = 4 * np.pi * 1e-7
        try:
            xls = pd.ExcelFile(path, engine='openpyxl')
            sheet = next((n for n in xls.sheet_names if n.lower() in ('simulation data', 'datasheet')), None)
            if sheet is None:
                return pd.DataFrame(), pd.DataFrame()
            df = pd.read_excel(path, sheet_name=sheet, header=1, engine='openpyxl')
            df = df[:-2].dropna(subset=['grade'])
            bh   = df[df['frequency [Hz]'] == 0].copy()
            loss = df[df['frequency [Hz]'] > 0].copy()
            for part in (bh, loss):
                if part.empty:
                    continue
                if 'permeability µr [1]' in part.columns:
                    part['B [T]'] = part['permeability µr [1]'] * mu0 * part['field strength H [A/m]']
                else:
                    part['B [T]'] = mu0 * part['field strength H [A/m]'] + part['polarisation J [T]']
            return bh, loss
        except Exception:
            return pd.DataFrame(), pd.DataFrame()


# %% ../../nbs/magnetics/02_electrical_steel.ipynb #eea0b7f7
# Note: The SteelDatabase class in the compiled module handles
# loading steel data from the literature folder.
# This section demonstrates how to use it.

def load_literature_database(literature_path: str | Path | None = None) -> 'SteelDatabase':
    """
    Create a SteelDatabase instance from the literature folder.
    
    The literature folder should have this structure:
    ```
    literature/datasheets/
    ├── Voelstapine Electrical Steel/     (Excel files)
    ├── SURA Electrical Steel/             (Excel files)  
    ├── Thyssenkrupp Electrical Steel/     (Excel files)
    └── steel_data_cache/                  (Pickle files - preprocessed)
        ├── sura_m470-50a.pkl
        ├── Simulation-data-isovac310-50A-voestalpine-*.pkl
        └── ...
    ```
    
    Parameters
    ----------
    literature_path : str or Path
        Path to the literature folder. If None, searches in:
        - ../KnowledgeBase/literature (relative to notebook)
        - ./KnowledgeBase/literature (relative to current dir)
        - Environment variable EMACHINES_LITERATURE
    
    Returns
    -------
    SteelDatabase
        Database instance with access to all 51+ steel grades
    
    Examples
    --------
    >>> db = load_literature_database()
    >>> db.grades  # List all available grades
    >>> db.manufacturers  # Group by manufacturer
    >>> steel = db.load('SURA M470-50A')
    >>> steel.loss_at(freq=400, B=1.5)  # Get core loss
    """
    import os
    
    if literature_path is None:
        # Search for literature folder
        candidates = [
            os.environ.get('EMACHINES_LITERATURE'),
            Path.cwd() / 'KnowledgeBase' / 'literature' / 'datasheets',
            Path.cwd() / '..' / 'KnowledgeBase' / 'literature' / 'datasheets',
        ]
        literature_path = None
        for candidate in candidates:
            if candidate and Path(candidate).exists():
                literature_path = candidate
                break
    
    literature_path = Path(literature_path) if literature_path else None
    
    if not literature_path or not literature_path.exists():
        raise FileNotFoundError(
            f"Literature datasheets directory not found at {literature_path}. "
            f"Expected structure: KnowledgeBase/literature/datasheets/"
        )
    
    return SteelDatabase(str(literature_path))  # type: ignore[arg-type]

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #408bea4c
# Load all real steel grades from literature
# This will be created on first import
_LITERATURE_STEELS: dict = {}  # Lazy-loaded on first access

def get_steel_library(reload: bool = False) -> dict[str, 'SteelGrade']:
    """Get dictionary of available steel grades from literature.
    
    Lazily loads steel grades from the KnowledgeBase/literature folder
    on first access.
    
    Parameters
    ----------
    reload : bool
        Force reload all steel data (default: False)
    
    Returns
    -------
    dict
        Dictionary mapping steel grade names to SteelGrade objects
    """
    global _LITERATURE_STEELS
    if reload or not _LITERATURE_STEELS:
        try:
            _LITERATURE_STEELS = load_literature_database()
        except FileNotFoundError:
            print("Warning: Literature folder not found. Using sample data only.")
            _LITERATURE_STEELS = {}
    return _LITERATURE_STEELS

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #5e628f9a
SAMPLE_BH: dict = {
    "M-19 Steel": {
        "H (A/m)": [0, 50, 100, 150, 200, 300, 400, 500, 1000, 1500, 2000, 3000, 4000, 5000],
        "B (T)":   [0, 0.6, 1.0, 1.2, 1.3, 1.4, 1.45, 1.5, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85],
    },
    "M-36 Steel": {
        "H (A/m)": [0, 40, 80, 120, 160, 240, 320, 400, 800, 1200, 1600, 2400, 3200, 4000],
        "B (T)":   [0, 0.5, 0.9, 1.1, 1.2, 1.3, 1.35, 1.4, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75],
    },
}

# %% ../../nbs/magnetics/02_electrical_steel.ipynb #c10ff4ed
SAMPLE_LOSS: dict = {
    "M-19 Steel": pd.DataFrame({
        "Frequency (Hz)":  [60, 60, 60, 60, 400, 400, 400, 400],
        "Flux Density (T)":[0.5, 1.0, 1.5, 1.7, 0.5, 1.0, 1.5, 1.7],
        "Core Loss (W/kg)":[0.4, 1.0, 1.8, 2.5, 4.0, 12.0, 25.0, 35.0],
    }),
    "M-36 Steel": pd.DataFrame({
        "Frequency (Hz)":  [60, 60, 60, 60, 400, 400, 400, 400],
        "Flux Density (T)":[0.5, 1.0, 1.5, 1.7, 0.5, 1.0, 1.5, 1.7],
        "Core Loss (W/kg)":[0.5, 1.2, 2.2, 3.0, 5.0, 15.0, 30.0, 42.0],
    }),
}
