# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/magnetics/03_iron_loss.ipynb.

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-ca2a56
from __future__ import annotations

import numpy as np
from scipy.optimize import curve_fit

# %% auto #0
__all__ = ['MODEL_NAMES', 'steinmetz', 'modified_steinmetz', 'bertotti', 'fit_steinmetz', 'fit_modified_steinmetz',
           'fit_bertotti', 'fit_loss_model']

# %% ../../nbs/magnetics/03_iron_loss.ipynb #d0843672
def steinmetz(
    f: float | np.ndarray,
    B_peak: float | np.ndarray,
    k: float,
    alpha: float,
    beta: float,
) -> float | np.ndarray:
    r"""Classical Steinmetz core loss model.
    P = k * f^alpha * B^beta
    Args:
        f: Frequency (Hz)
        B_peak: Peak flux density (T)
        k: Material constant
        alpha: Frequency exponent (1.0–1.6)
        beta: Flux density exponent (1.6–2.2)
    Returns:
        Core loss (W/kg)
    """
    return k * (np.asarray(f) ** alpha) * (np.asarray(B_peak) ** beta)

# %% ../../nbs/magnetics/03_iron_loss.ipynb #b9bfbdbd
def modified_steinmetz(
    f: float | np.ndarray,
    B_peak: float | np.ndarray,
    k: float,
    alpha: float,
    beta: float,
) -> float | np.ndarray:
    r"""Modified Steinmetz (iGSE) for PWM waveforms.
    P = k * f^(alpha-1) * (f*B)^beta
    Args:
        f: Frequency (Hz)
        B_peak: Peak flux density (T)
        k: Material constant
        alpha: Frequency exponent
        beta: Combined exponent
    Returns:
        Core loss (W/kg)
    """
    f = np.asarray(f)
    B = np.asarray(B_peak)
    return k * (f ** (alpha - 1)) * ((f * B) ** beta)

# %% ../../nbs/magnetics/03_iron_loss.ipynb #2f904fdf
def bertotti(
    f: float | np.ndarray,
    B_peak: float | np.ndarray,
    k_h: float,
    k_e: float,
    k_a: float,
    alpha: float = 1.0,
    beta: float = 2.0,
) -> dict[str, float | np.ndarray]:
    r"""Bertotti three-term iron loss separation.
    Separates into hysteresis, eddy, and excess components.
    Args:
        f: Frequency (Hz)
        B_peak: Peak flux density (T)
        k_h: Hysteresis coefficient
        k_e: Eddy current coefficient
        k_a: Excess coefficient
        alpha: Frequency exponent (default 1.0)
        beta: Flux density exponent (default 2.0)
    Returns:
        Dict with 'hysteresis', 'eddy', 'excess', 'total' (W/kg)
    """
    f = np.asarray(f)
    B = np.asarray(B_peak)
    p_hyst = k_h * (f ** alpha) * (B ** beta)
    p_eddy = k_e * (f * B) ** 2
    p_exc  = k_a * (f * B) ** 1.5
    return {
        "hysteresis": p_hyst,
        "eddy": p_eddy,
        "excess": p_exc,
        "total": p_hyst + p_eddy + p_exc,
    }

# %% ../../nbs/magnetics/03_iron_loss.ipynb #cc991a12
def fit_steinmetz(
    f_arr: np.ndarray,
    B_arr: np.ndarray,
    loss_arr: np.ndarray,
) -> dict:
    """Fit Steinmetz parameters (k, α, β) to measured data."""
    def _func(X, k, alpha, beta):
        return steinmetz(X[0], X[1], k, alpha, beta)
    popt, _ = curve_fit(_func, (f_arr, B_arr), loss_arr,
                        p0=[0.01, 1.5, 2.5], maxfev=10000)
    fitted = _func((f_arr, B_arr), *popt)
    ss_res = np.sum((loss_arr - fitted) ** 2)
    r2 = 1.0 - ss_res / np.sum((loss_arr - np.mean(loss_arr)) ** 2)
    rmse = float(np.sqrt(np.mean((loss_arr - fitted) ** 2)))
    return {"k": popt[0], "alpha": popt[1], "beta": popt[2],
            "r2": float(r2), "rmse": rmse, "model": "Steinmetz"}

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-4f3887
MODEL_NAMES = ("Bertotti", "Steinmetz", "Modified Steinmetz")

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-58b1da
def _r2_rmse(y_true, y_pred):
    """Return (R², RMSE) for a fit."""
    ss_res = np.sum((y_true - y_pred) ** 2)
    r2 = 1.0 - ss_res / np.sum((y_true - np.mean(y_true)) ** 2)
    rmse = float(np.sqrt(np.mean((y_true - y_pred) ** 2)))
    return float(r2), rmse

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-928365
def fit_modified_steinmetz(
    f_arr: np.ndarray,
    B_arr: np.ndarray,
    loss_arr: np.ndarray,
) -> dict:
    """Fit Modified Steinmetz (iGSE) parameters (k, α, β)."""
    def _func(X, k, alpha, beta):
        return modified_steinmetz(X[0], X[1], k, alpha, beta)
    popt, _ = curve_fit(_func, (f_arr, B_arr), loss_arr, p0=[0.01, 1.5, 2.0], maxfev=10000)
    fitted = _func((f_arr, B_arr), *popt)
    r2, rmse = _r2_rmse(loss_arr, fitted)
    return {"k": popt[0], "alpha": popt[1], "beta": popt[2],
            "r2": r2, "rmse": rmse, "model": "Modified Steinmetz"}

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-3f4a60
def fit_bertotti(
    f_arr: np.ndarray,
    B_arr: np.ndarray,
    loss_arr: np.ndarray,
) -> dict:
    """Fit Bertotti three-term parameters (kh, ke, ka)."""
    def _func(X, kh, ke, ka):
        return bertotti(X[0], X[1], kh, ke, ka)["total"]
    popt, _ = curve_fit(_func, (f_arr, B_arr), loss_arr, p0=[0.01, 0.0001, 0.001], maxfev=10000)
    fitted = _func((f_arr, B_arr), *popt)
    r2, rmse = _r2_rmse(loss_arr, fitted)
    return {"k_h": popt[0], "k_e": popt[1], "k_a": popt[2],
            "r2": r2, "rmse": rmse, "model": "Bertotti"}

# %% ../../nbs/magnetics/03_iron_loss.ipynb #nbdev-31dfd2
def fit_loss_model(
    f_arr: np.ndarray,
    B_arr: np.ndarray,
    loss_arr: np.ndarray,
    model: str = "Bertotti",
) -> dict:
    """Fit a named core loss model. model must be one of MODEL_NAMES."""
    f_arr    = __import__("numpy").asarray(f_arr,    dtype=float)
    B_arr    = __import__("numpy").asarray(B_arr,    dtype=float)
    loss_arr = __import__("numpy").asarray(loss_arr, dtype=float)
    if model == "Bertotti":           return fit_bertotti(f_arr, B_arr, loss_arr)
    elif model == "Steinmetz":        return fit_steinmetz(f_arr, B_arr, loss_arr)
    elif model == "Modified Steinmetz": return fit_modified_steinmetz(f_arr, B_arr, loss_arr)
    else: raise ValueError(f"Unknown model '{model}'. Choose from: {MODEL_NAMES}")
