"""Root package init — sets `__version__`. All public symbols live in subpackages (`winding`, `magnetics`, `motors`, `mec`).

Docs: https://NaveenDeepak.github.io/emachinesinit.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_init.ipynb #c3d4e5f6
"""emachines — Analytical electromechanical machine design library."""

from typing import List

__version__ = "0.6.0"
__all__: List[str] = []
