"""Analytical electromechanical machine design library

Modules:

- `emachines.mec.solver`: Magnetic Equivalent Circuit (MEC) solver.
- `emachines.motors..ipynb_checkpoints.motors-checkpoint`: Electric Motors Module: DC and PMSM models
- `emachines.winding.factors`: Deprecated: this module has been renamed to winding_factors.py."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_init.ipynb #c3d4e5f6
"""emachines — Analytical electromechanical machine design library."""

from typing import List

__version__ = "0.6.0"
__all__: List[str] = []
