# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/test_verify.ipynb.

# %% auto #0
__all__ = ['test_function']

# %% ../nbs/test_verify.ipynb #d08d1201-4445-44a7-b2f9-72b11a05af41
def test_function(x: int) -> int:
    return x + 1
