# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_material_models.ipynb.

# %% ../../nbs/04_material_models.ipynb #nbdev-314ae1
from __future__ import annotations

import math
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional

import numpy as np
from scipy.interpolate import CubicSpline

# %% auto #0
__all__ = ['MU0', 'PermeabilityModel', 'LinearPermeabilityModel', 'SplinePermeabilityModel', 'ShanesudhoffModel']

# %% ../../nbs/04_material_models.ipynb #c49b67a2
MU0 = 4e-7 * np.pi  # H/m

class PermeabilityModel(ABC):
    """Abstract interface for permeability models used by the MEC solver."""

    @abstractmethod
    def mu(self, B: float) -> float:
        r"""Return permeability μ [H/m] at flux density *B* [T]."""

    @abstractmethod
    def dmu_dB(self, B: float) -> float:
        r"""Return dμ/dB [H/m·T⁻¹] at flux density *B* [T]."""
        pass

# %% ../../nbs/04_material_models.ipynb #ba02550b
class LinearPermeabilityModel(PermeabilityModel):
    """
    Constant permeability μ = μ₀ · μᵣ.

    Parameters
    ----------
    mu_r:
        Relative permeability (dimensionless). Default is 1 (free space).
    """

    def __init__(self, mu_r: float = 1.0) -> None:
        if mu_r <= 0:
            raise ValueError(f"mu_r must be positive, got {mu_r}")
        self._mu = MU0 * mu_r

    def mu(self, B: float) -> float:
        """Return constant permeability."""
        return self._mu

    def dmu_dB(self, B: float) -> float:
        """Derivative is zero for linear model."""
        return 0.0

# %% ../../nbs/04_material_models.ipynb #0db5b47b
class SplinePermeabilityModel(PermeabilityModel):
    """
    Permeability model built from tabulated B-H data via a cubic spline.

    The data are assumed to start at (H=0, B=0). Negative-B evaluation
    uses odd symmetry: μ(−|B|) = μ(|B|), dμ/dB(−|B|) = −dμ/dB(|B|).

    Parameters
    ----------
    H_data:
        Array of field strengths [A/m], monotonically increasing from 0.
    B_data:
        Corresponding flux densities [T].

    Class methods
    -------------
    from_steel_grade(grade)
        Convenience constructor that reads the ``bh_data`` DataFrame of an
        :class:`emachines.magnetics.SteelGrade` instance.
    """

    def __init__(
        self,
        H_data,  # Sequence[float]
        B_data,  # Sequence[float]
    ) -> None:
        H = np.asarray(H_data, dtype=float)
        B = np.asarray(B_data, dtype=float)

        if H.shape != B.shape:
            raise ValueError("H_data and B_data must have the same length.")
        if H[0] != 0.0 or B[0] != 0.0:
            raise ValueError("B-H data must start at (H=0, B=0).")
        if not np.all(np.diff(H) > 0):
            raise ValueError("H_data must be strictly increasing.")

        # μ(B) = μ₀ * H/B — defined for B > 0 only
        B_pos = B[1:]
        H_pos = H[1:]
        mu_pos = MU0 * H_pos / B_pos

        # Prepend B=0 using initial linear slope
        mu_at_0 = MU0 * H_pos[0] / B_pos[0]
        B_knots = np.concatenate([[0.0], B_pos])
        mu_knots = np.concatenate([[mu_at_0], mu_pos])

        self._B_max = B_knots[-1]
        self._mu_min = mu_knots[-1]
        self._cs = CubicSpline(B_knots, mu_knots)
        self._cs_deriv = self._cs.derivative()

    @classmethod
    def from_steel_grade(cls, grade) -> "SplinePermeabilityModel":
        """
        Create a SplinePermeabilityModel from a
        :class:`emachines.magnetics.SteelGrade`.
        """
        df = grade.bh_data
        # Find H and B columns by substring match
        h_col = next(c for c in df.columns if "H" in c.upper() and "B" not in c.upper())
        b_col = next(c for c in df.columns if c.upper().startswith("B"))
        H = df[h_col].to_numpy(dtype=float)
        B = df[b_col].to_numpy(dtype=float)
        # Sort and ensure starts at origin
        order = np.argsort(H)
        H, B = H[order], B[order]
        if H[0] != 0:
            H = np.concatenate([[0.0], H])
            B = np.concatenate([[0.0], B])
        return cls(H, B)

    def mu(self, B: float) -> float:
        """Return permeability at flux density B."""
        absB = abs(B)
        if absB >= self._B_max:
            return self._mu_min
        return float(self._cs(absB))

    def dmu_dB(self, B: float) -> float:
        """Return derivative dμ/dB at flux density B."""
        absB = abs(B)
        if absB >= self._B_max:
            return 0.0
        sign = 1.0 if B >= 0 else -1.0
        return sign * float(self._cs_deriv(absB))

# %% ../../nbs/04_material_models.ipynb #8f990763
class ShanesudhoffModel(PermeabilityModel):
    """
    Shane-Sudhoff (2010) analytical permeability model.

    Parameters
    ----------
    mu_r:
        Initial relative permeability.
    a, b, gamma:
        Sequences of equal length, one entry per term.
    mu0:
        Permeability of free space [H/m]. Default: 4π×10⁻⁷.

    Class methods
    -------------
    ferrite_3C90()
        Returns a ShanesudhoffModel with the 3C90 ferrite parameters from
        the MEC 3.2 toolbox example (Sudhoff, 2014).
    """

    def __init__(
        self,
        mu_r: float,
        a,  # Sequence[float]
        b,  # Sequence[float]
        gamma,  # Sequence[float]
        mu0: float = None,
    ) -> None:
        if mu0 is None:
            mu0 = MU0
        a = np.asarray(a, dtype=float)
        b = np.asarray(b, dtype=float)
        gamma = np.asarray(gamma, dtype=float)
        if not (len(a) == len(b) == len(gamma)):
            raise ValueError("a, b, gamma must all have the same length.")

        self._mu_r = float(mu_r)
        self._a = a
        self._b = b
        self._mu0 = float(mu0)

        # Pre-compute derived constants
        self._d = a / b
        self._z = (gamma - 1.0) / gamma
        self._e = 1.0 - self._z
        self._h = self._mu0 * a * self._z * b

    def _f_and_df(self, absB: float):
        """Return (f, df/d|B|) at |B|."""
        eb = np.exp(-self._b * absB)
        arg = self._e + self._z * eb

        sum_terms = np.sum(self._a * absB + self._d * np.log(arg))
        f = self._mu_r / (self._mu_r - 1.0) + sum_terms

        dlog_dabs = -self._d * self._z * self._b * eb / arg
        df = np.sum(self._a + dlog_dabs)

        return f, df

    def mu(self, B: float) -> float:
        """Return permeability at flux density B."""
        absB = abs(float(B))
        f, _ = self._f_and_df(absB)
        return self._mu0 * f / (f - 1.0)

    def dmu_dB(self, B: float) -> float:
        """Return derivative dμ/dB at flux density B."""
        absB = abs(float(B))
        f, df = self._f_and_df(absB)
        fm1 = f - 1.0
        sign = 1.0 if B >= 0 else -1.0
        return -self._mu0 * df / (fm1 * fm1) * sign

    @classmethod
    def ferrite_3C90(cls) -> "ShanesudhoffModel":
        """
        3C90 ferrite parameters from MEC 3.2 toolbox (Sudhoff, 2014).

        μᵣ = 22 340.9259
        """
        return cls(
            mu_r=22340.9259,
            a=[1.1542, 0.049742, 0.049644, 0.041155],
            b=[431.1763, 2.29503, 15.04824, 74.28908],
            gamma=[0.4742, 2.7955, 0.59862, 0.43996],
        )
