# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/motors/03_api.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/motors/03_api.ipynb #api-69804809f610d308
from .dc_motor import GeometricParams, MaterialProperties, OperatingConditions, LumpedParams, calculate_carter_coefficient, calculate_magnetic_circuit
from .pmsm import PMSMParams, back_emf, torque, dq_currents, SPM

__all__ = ['GeometricParams', 'MaterialProperties', 'OperatingConditions', 'LumpedParams', 'calculate_carter_coefficient', 'calculate_magnetic_circuit', 'PMSMParams', 'back_emf', 'torque', 'dq_currents', 'SPM']
