# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/motors/01_pmsm.ipynb.

# %% ../../nbs/motors/01_pmsm.ipynb #nbdev-f2d05e
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np

# %% auto #0
__all__ = ['PMSMParams', 'back_emf', 'torque', 'dq_currents', 'SPM']

# %% ../../nbs/motors/01_pmsm.ipynb #e1860bdd
class PMSMParams:
    """Container for PMSM parameters."""
    def __init__(self, p: int, Ld: float, Lq: float, psi_m: float, Rs: float = 0.0, J: float = 0.0):
        self.p = p
        self.Ld = Ld
        self.Lq = Lq
        self.psi_m = psi_m
        self.Rs = Rs
        self.J = J

    @property
    def is_spm(self) -> bool:
        """True if surface-mount (Ld ≈ Lq)."""
        return bool(np.isclose(self.Ld, self.Lq, rtol=0.05))

# %% ../../nbs/motors/01_pmsm.ipynb #bc66361f
def back_emf(omega_e: float, psi_m: float) -> float:
    """Peak phase back-EMF."""
    return omega_e * psi_m

# %% ../../nbs/motors/01_pmsm.ipynb #1fd66380
def torque(params: PMSMParams, id: float, iq: float) -> float:
    """Electromagnetic torque."""
    T_excitation = params.psi_m * iq
    T_reluctance = (params.Ld - params.Lq) * id * iq
    return 1.5 * params.p * (T_excitation + T_reluctance)

# %% ../../nbs/motors/01_pmsm.ipynb #4f79a4a7
def dq_currents(params: PMSMParams, omega_e: float, Vd: float, Vq: float) -> tuple[float, float]:
    """Steady-state dq currents."""
    A = np.array([[params.Rs, -omega_e * params.Lq],
                  [omega_e * params.Ld, params.Rs]])
    b = np.array([Vd, Vq - omega_e * params.psi_m])
    id_, iq_ = np.linalg.solve(A, b)
    return float(id_), float(iq_)

# %% ../../nbs/motors/01_pmsm.ipynb #7fa0c9f5
class SPM:
    """Surface-Mount PMSM motor profile."""
    def __init__(self, phi_m: float, ld: float, pp: int, Vb: float, Ib: float):
        self.phi_m = phi_m
        self.sal = 0
        self.ld = ld
        self.Vb = Vb
        self.Ib = Ib
        self.Pb = 1.5 * Vb * Ib
        self.pp = pp
        self.speed: list[float] = []
        self.torque: list[float] = []
        self.voltage: list[float] = []
        self.gamma: list[float] = []
        self.power: list[float] = []
        self.valid = 0

    def validate(self) -> bool:
        """Check parameter validity."""
        self.valid = 1 if self.sal == 0 else 0
        return self.valid == 1

    def motor_profile(self) -> None:
        """Compute torque-speed profile."""
        self.speed: list[float] = []
        self.torque: list[float] = []
        self.voltage: list[float] = []
        self.gamma: list[float] = []
        self.power: list[float] = []
        gamma_deg = 0
        gamma = 0.0
        omega = 0.0
        v = 0.0
        v_lim = self.Vb / 1.732
        while v < v_lim:
            v = omega * self.pp * np.sqrt(
                (self.phi_m - self.Ib * np.sin(gamma) * self.ld) ** 2
                + (self.Ib * self.ld * np.cos(gamma)) ** 2
            )
            t = 1.5 * self.pp * self.phi_m * self.Ib * np.cos(gamma)
            p = t * omega
            omega += 0.1
            self.speed.append(omega * 30 / np.pi)
            self.voltage.append(v)
            self.gamma.append(gamma_deg)
            self.torque.append(t)
            self.power.append(p)
        for gamma_deg in range(1, 85):
            gamma = gamma_deg * np.pi / 180
            omega = (v_lim) / (self.pp * np.sqrt(
                (self.phi_m - self.Ib * np.sin(gamma) * self.ld) ** 2
                + (self.Ib * self.ld * np.cos(gamma)) ** 2
            ))
            t = 1.5 * self.pp * self.Ib * self.phi_m * np.cos(gamma)
            p = t * omega
            self.speed.append(omega * 30 / np.pi)
            self.voltage.append(v)
            self.gamma.append(gamma_deg)
            self.torque.append(t)
            self.power.append(p)
