# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/winding/02_mmf.ipynb.

# %% ../../nbs/winding/02_mmf.ipynb #aa3c8b12
from __future__ import annotations

import numpy as np

from .sos import build_coil_matrix
from .winding_factors import _optimal_coil_span, winding_factor_spectrum

# %% auto #0
__all__ = ['mmf_distribution', 'mmf_waveform', 'mmf_harmonics']

# %% ../../nbs/winding/02_mmf.ipynb #5c1d4f02
def _phase_currents(m: int, theta_electrical: float) -> np.ndarray:
    """
    Instantaneous balanced m-phase currents (per-unit peak = 1).

    .. math::
        i_k = \\cos(\\theta_e - 2\\pi k / m), \\quad k = 0, 1, \\ldots, m-1

    Parameters
    ----------
    m                : int    Number of phases
    theta_electrical : float  Electrical time angle (radians)

    Returns
    -------
    np.ndarray, shape (m,)
    """
    k = np.arange(m, dtype=np.float64)
    return np.cos(theta_electrical - 2.0 * np.pi * k / m)

# %% ../../nbs/winding/02_mmf.ipynb #c9e7b25a
def mmf_distribution(
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
    theta_electrical: float = 0.0,
) -> np.ndarray:
    r"""
    Instantaneous signed ampere-conductor distribution along the airgap.

    For each slot position *i* (mechanical angle θᵢ = 2π·i/Q), ``n[i]``
    is the sum of signed conductor currents across all winding layers:

    .. math::
        n_i = \sum_{\text{layer}} \operatorname{sign}(\text{code}_{i,\text{layer}})
              \cdot i_{\,|\text{code}|-1}(\theta_e)

    Parameters
    ----------
    Q                : int    Number of stator slots
    P                : int    Number of poles (even, ≥ 2)
    m                : int    Number of phases (default 3)
    layers           : int    1 (single-layer) or 2 (double-layer)
    w                : int | None
                              Coil span in slots. ``None`` → coil span that
                              maximises the fundamental winding factor.
    theta_electrical : float  Electrical time angle (radians, default 0).

    Returns
    -------
    np.ndarray, shape (Q,), dtype float64
        Signed ampere-conductor value at each slot. Per-unit (peak = 1 A·turn).

    Examples
    --------
    >>> n = mmf_distribution(12, 10, layers=2)
    >>> n.shape
    (12,)
    >>> abs(n.sum()) < 1e-10
    True
    """
    if w is None:
        w = _optimal_coil_span(Q, P, m, layers)

    matrix = build_coil_matrix(Q, P, m, layers, w)   # shape (layers, Q)
    i_ph = _phase_currents(m, theta_electrical)        # shape (m,)

    n = np.zeros(Q, dtype=np.float64)
    for lyr in range(layers):
        for i in range(Q):
            code = int(matrix[lyr, i])
            if code == 0:
                continue
            k = abs(code) - 1          # 0-based phase index
            sign = 1 if code > 0 else -1
            n[i] += sign * i_ph[k]

    return n

# %% ../../nbs/winding/02_mmf.ipynb #d4e7c813
def mmf_waveform(
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
    theta_electrical: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    r"""
    Instantaneous MMF staircase waveform along the airgap.

    Applies Ampere's law around the stator bore: the MMF at mechanical
    angle θ equals the cumulative sum of ampere-conductors from slot 0
    up to the slot preceding θ, with the DC offset removed.

    .. math::
        F(\theta_i) = \sum_{j=0}^{i-1} n_j - \overline{F}

    The staircase is returned *closed* (first point repeated at 360°)
    for direct use in step-line plots.

    Parameters
    ----------
    Q                : int
    P                : int
    m                : int    (default 3)
    layers           : int    1 or 2 (default 1)
    w                : int | None
    theta_electrical : float  Electrical time angle (radians, default 0)

    Returns
    -------
    angles : np.ndarray, shape (Q + 1,)
        Mechanical angles in degrees, 0° … 360° inclusive.
    F      : np.ndarray, shape (Q + 1,)
        Per-unit MMF at each slot boundary (closed staircase).

    Examples
    --------
    >>> angles, F = mmf_waveform(12, 10, layers=2)
    >>> angles.shape, F.shape
    ((13,), (13,))
    >>> abs(F.mean()) < 1e-10
    True
    """
    if w is None:
        w = _optimal_coil_span(Q, P, m, layers)

    n = mmf_distribution(Q, P, m, layers, w, theta_electrical)

    F = np.cumsum(n)
    F -= F.mean()

    angles = np.linspace(0.0, 360.0, Q, endpoint=False)
    angles = np.append(angles, 360.0)
    F = np.append(F, F[0])

    return angles, F

# %% ../../nbs/winding/02_mmf.ipynb #ab1f9e42
def mmf_harmonics(
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
    mode: str = "three_phase",
    nu_max: int = 40,
    normalize: bool = True,
) -> tuple[np.ndarray, np.ndarray]:
    r"""
    MMF harmonic amplitude spectrum.

    The amplitude of spatial harmonic ν in the airgap MMF:

    .. math::
        \hat{F}_\nu = \frac{k_{w\nu} \cdot p}{\nu}

    For ``mode="three_phase"`` harmonics cancelled by the balanced
    m-phase current sum are identified numerically and zeroed out.

    Parameters
    ----------
    Q      : int
    P      : int
    m      : int    Number of phases (default 3)
    layers : int    (default 1)
    w      : int | None
    mode   : str
        ``"three_phase"``    — balanced m-phase MMF; zero-sequence harmonics
                               cancelled numerically (default).
        ``"single_phase"``   — single-phase MMF; all harmonics retained.
        ``"winding_factor"`` — returns |kw(ν)| with no 1/ν weighting.
    nu_max    : int   Maximum harmonic order (default 40)
    normalize : bool
        ``True``  (default) — divide by the working-harmonic amplitude
                              so the working harmonic = 1.0.
        ``False`` — return raw kw(ν)·p/ν values.

    Returns
    -------
    nu_arr : np.ndarray, shape (nu_max,), dtype int
        Mechanical harmonic orders 1 … nu_max.
    amp    : np.ndarray, shape (nu_max,), dtype float64
        Harmonic amplitudes.

    Examples
    --------
    >>> nu, amp = mmf_harmonics(12, 10, layers=2, normalize=True)
    >>> float(round(amp[4], 4))   # working harmonic (ν=5) should be 1.0
    1.0
    >>> nu, amp = mmf_harmonics(12, 10, layers=2, mode="single_phase",
    ...                         normalize=False)
    >>> amp[4] > 0
    True

    References
    ----------
    Pyrhönen et al. (2014), §2.4, eq. (2.98).
    Müller, Vogt & Ponick (2008), eq. (3.65).
    """
    p = P // 2
    if w is None:
        w = _optimal_coil_span(Q, P, m, layers)

    nu_arr, kw_arr = winding_factor_spectrum(Q, P, m, layers, w, nu_max=nu_max)
    kw_abs = np.abs(kw_arr)

    if mode == "winding_factor":
        amp = kw_abs.copy()
        if normalize:
            fund = kw_abs[p - 1] if p <= nu_max else 0.0
            if fund < 1e-10:
                fund = kw_abs.max() if kw_abs.max() > 1e-10 else 1.0
            amp /= fund
        return nu_arr, amp

    # Raw MMF amplitude: kw(ν)·p / ν
    amp = kw_abs * p / nu_arr.astype(np.float64)

    if mode == "three_phase":
        # Numerically detect harmonics cancelled by the balanced m-phase sum.
        # Forward (positive-sequence) and backward (negative-sequence) phasors
        # are both checked; a harmonic survives if either is non-zero.
        matrix = build_coil_matrix(Q, P, m, layers, w)
        slots = np.arange(Q, dtype=np.float64)

        i_fwd = np.exp(-1j * 2.0 * np.pi * np.arange(m) / m)
        i_bwd = np.exp(+1j * 2.0 * np.pi * np.arange(m) / m)

        for idx, nu in enumerate(nu_arr):
            phasors = np.exp(1j * nu * 2.0 * np.pi * slots / Q)
            T_f = T_b = 0j
            for k in range(m):
                ph = k + 1
                ph_sum = 0j
                for lyr in range(layers):
                    fwd = matrix[lyr] == +ph
                    ret = matrix[lyr] == -ph
                    ph_sum += phasors[fwd].sum() - phasors[ret].sum()
                T_f += i_fwd[k] * ph_sum
                T_b += i_bwd[k] * ph_sum
            if max(abs(T_f), abs(T_b)) < 1e-6:
                amp[idx] = 0.0

    if normalize:
        fund = amp[p - 1] if p <= nu_max else 0.0
        if fund < 1e-10:
            fund = amp.max() if amp.max() > 1e-10 else 1.0
        amp = amp / fund

    return nu_arr, amp
