# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/winding/03_sos.ipynb.

# %% ../../nbs/winding/03_sos.ipynb #d9dd98f4
from __future__ import annotations

import math
from functools import lru_cache
from fractions import Fraction
from math import gcd

import numpy as np

# %% auto #0
__all__ = ['get_basic_params', 'build_star_of_slots', 'assign_phases', 'build_coil_matrix', 'winding_factor_sos',
           'check_symmetry', 'get_valid_coil_spans', 'is_valid_combination']

# %% ../../nbs/winding/03_sos.ipynb #68a71fc6
def _lcm(a: int, b: int) -> int:
    """Least common multiple of two positive integers."""
    return a * b // gcd(a, b)


def _angular_distance(a: float, b: float) -> float:
    """
    Smallest angular distance between two angles (radians), in [0, π].
    """
    d = abs(a - b) % (2 * math.pi)
    return min(d, 2 * math.pi - d)

# %% ../../nbs/winding/03_sos.ipynb #7f7667e3
def get_basic_params(Q: int, P: int, m: int = 3) -> dict:
    """
    Compute basic winding parameters from slot/pole/phase count.

    Parameters
    ----------
    Q : int   Number of stator slots
    P : int   Number of poles (even)
    m : int   Number of phases (default 3)

    Returns
    -------
    dict with keys:
        p       : int   Pole pairs (P // 2)
        t       : int   Winding periodicity = gcd(Q, p)
        q       : Fraction   Slots per pole per phase = Q / (2mp)
        lcm_QP  : int   lcm(Q, P)
        alpha_e : float Electrical slot pitch (radians) = p · 2π/Q
        Q_phase : int   Slots per phase = Q // m  (integer part)

    Examples
    --------
    >>> p = get_basic_params(12, 10)
    >>> p['p'], p['t']
    (5, 1)
    >>> p = get_basic_params(24, 4)
    >>> p['q']
    Fraction(2, 1)
    """
    p = P // 2
    t = gcd(Q, p)
    q = Fraction(Q, 2 * m * p)
    lcm_QP = _lcm(Q, P)
    alpha_e = p * 2 * math.pi / Q
    Q_phase = Q // m
    return dict(p=p, t=t, q=q, lcm_QP=lcm_QP, alpha_e=alpha_e, Q_phase=Q_phase)

# %% ../../nbs/winding/03_sos.ipynb #3836897f
def build_star_of_slots(Q: int, P: int) -> np.ndarray:
    """
    Compute EMF phasor angles for all Q slots (electrical radians, mod 2π).

    Parameters
    ----------
    Q : int   Number of stator slots
    P : int   Number of poles

    Returns
    -------
    np.ndarray, shape (Q,), dtype float64
        Phasor angles α_i = i · p · 2π/Q mod 2π

    Examples
    --------
    >>> import numpy as np
    >>> angles = build_star_of_slots(6, 2)
    >>> np.round(angles, 4)
    array([0.    , 1.0472, 2.0944, 3.1416, 4.1888, 5.236 ])
    """
    p = P // 2
    alpha_e = p * 2 * math.pi / Q
    return np.array([(i * alpha_e) % (2 * math.pi) for i in range(Q)],
                    dtype=np.float64)

# %% ../../nbs/winding/03_sos.ipynb #2356d58a
def _assign_slot_to_phase(angle: float, m: int) -> int:
    """
    Return the signed phase code for a slot at electrical angle `angle`.

    Uses floor-division sector assignment: the electrical circle [0, 2π) is
    divided into 2m sectors of width π/m each. Sector k contains angles
    [k·π/m, (k+1)·π/m). Phase codes: k < m → +(k+1), k >= m → -(k-m+1).

    Returns
    -------
    int in {+1…+m, -1…-m}
    """
    sector_width = math.pi / m
    # Small epsilon pushes exact-boundary angles into the right sector
    k = int((angle % (2 * math.pi) + 1e-9) / sector_width) % (2 * m)
    if k < m:
        return k + 1
    else:
        return -(k - m + 1)


# %% ../../nbs/winding/03_sos.ipynb #11ccc4b9
def assign_phases(Q: int, P: int, m: int = 3) -> np.ndarray:
    """
    Assign each slot to a phase and current direction using the star-of-slots.

    Parameters
    ----------
    Q : int   Number of stator slots
    P : int   Number of poles
    m : int   Number of phases (default 3)

    Returns
    -------
    np.ndarray, shape (Q,), dtype int
        Signed phase codes: +k = phase k forward, −k = phase k return.
        Phase index k ∈ {1, …, m}.

    Examples
    --------
    >>> assign_phases(6, 2, m=3)
    array([ 1,  2,  3, -1, -2, -3])
    """
    angles = build_star_of_slots(Q, P)
    return np.array([_assign_slot_to_phase(a, m) for a in angles], dtype=int)

# %% ../../nbs/winding/03_sos.ipynb #35768883
def build_coil_matrix(
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
) -> np.ndarray:
    """
    Build the (layers × Q) conductor occupancy matrix.

    Parameters
    ----------
    Q      : int         Number of stator slots
    P      : int         Number of poles
    m      : int         Number of phases (default 3)
    layers : int         1 (single-layer) or 2 (double-layer)
    w      : int | None  Coil span in slots. None → Q // (P // 2).

    Returns
    -------
    np.ndarray, shape (layers, Q), dtype int
        +k = phase k forward, −k = phase k return, 0 = empty.

    Examples
    --------
    >>> build_coil_matrix(6, 2, m=3, layers=1).tolist()
    [[1, 2, 3, -1, -2, -3]]
    >>> build_coil_matrix(6, 2, m=3, layers=2, w=3).shape
    (2, 6)
    """
    p = P // 2
    if w is None:
        w = max(1, Q // P)  # pole pitch in slots (τp = Q/P, floored)

    phase_codes = assign_phases(Q, P, m)   # go-conductor assignment

    matrix = np.zeros((layers, Q), dtype=int)

    if layers == 1:
        # Place go conductors in all Q slots (single-layer → no return needed here;
        # the return side is implicit in the slot diametrically opposite).
        for i in range(Q):
            matrix[0, i] = phase_codes[i]
    else:
        # Double-layer: top layer = go conductors, bottom layer = return conductors
        # shifted by coil span w.
        for i in range(Q):
            go_code  = phase_codes[i]
            ret_slot = (i + w) % Q
            matrix[0, i]        = +go_code
            matrix[1, ret_slot] = -go_code

    return matrix

# %% ../../nbs/winding/03_sos.ipynb #e3d9179b
def winding_factor_sos(
    nu: int,
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
) -> float:
    """
    Winding factor |kw(ν)| via the star-of-slots phasor method.

    Works for integer-slot, fractional-slot, and FSCW windings.

    Parameters
    ----------
    nu     : int         Mechanical harmonic order
    Q      : int         Number of stator slots
    P      : int         Number of poles
    m      : int         Number of phases (default 3)
    layers : int         1 or 2 (default 1)
    w      : int | None  Coil span. None → Q // (P // 2).

    Returns
    -------
    float   |kw(ν)| ∈ [0, 1]

    Examples
    --------
    >>> round(winding_factor_sos(5, 12, 10, layers=2), 4)
    0.933
    >>> round(winding_factor_sos(4, 12, 8, layers=2), 4)
    0.866
    """
    matrix = build_coil_matrix(Q, P, m, layers, w)
    slots = np.arange(Q, dtype=np.float64)
    phasors = np.exp(1j * nu * 2.0 * np.pi * slots / Q)

    kw_vals = []
    for k in range(m):
        ph = k + 1
        total = 0j
        n_cond = 0
        for lyr in range(layers):
            fwd = matrix[lyr] == +ph
            ret = matrix[lyr] == -ph
            total += phasors[fwd].sum() - phasors[ret].sum()
            n_cond += int(fwd.sum()) + int(ret.sum())
        if n_cond > 0:
            kw_vals.append(abs(total) / n_cond)

    return float(np.mean(kw_vals)) if kw_vals else 0.0

# %% ../../nbs/winding/03_sos.ipynb #72d86813
def check_symmetry(Q: int, P: int, m: int = 3, layers: int = 1) -> dict:
    """
    Check if the winding has the expected symmetry.

    Parameters
    ----------
    Q      : int   Number of stator slots
    P      : int   Number of poles
    m      : int   Number of phases (default 3)
    layers : int   1 or 2 (default 1)

    Returns
    -------
    dict with keys:
        balanced     : bool   True if all phases carry equal conductors
        conductors   : list   Conductor count per phase [n_A, n_B, n_C, …]
        periodicity  : int    Winding periodicity t = gcd(Q, p)
        q            : Fraction   Slots per pole per phase
        valid        : bool   True if balanced AND Q % m == 0

    Examples
    --------
    >>> r = check_symmetry(12, 10, layers=2)
    >>> r['balanced'], r['valid']
    (True, True)
    >>> r = check_symmetry(12, 4, layers=1)
    >>> r['balanced']
    True
    """
    p = P // 2
    t = gcd(Q, p)
    q = Fraction(Q, 2 * m * p)

    matrix = build_coil_matrix(Q, P, m, layers)
    conductors = []
    for k in range(m):
        ph = k + 1
        cnt = sum(
            int((matrix[lyr] == +ph).sum()) + int((matrix[lyr] == -ph).sum())
            for lyr in range(layers)
        )
        conductors.append(cnt)

    balanced = len(set(conductors)) == 1
    valid = balanced and (Q % m == 0)

    return dict(balanced=balanced, conductors=conductors, periodicity=t, q=q, valid=valid)

# %% ../../nbs/winding/03_sos.ipynb #cb9c9e82
def get_valid_coil_spans(Q: int, P: int, m: int = 3) -> list[int]:
    """
    Return all coil spans (in slots) that yield a balanced winding.

    Evaluates spans 1 … Q//(P//2) and keeps those where all m phases
    carry an equal number of conductors in the double-layer assignment.

    Parameters
    ----------
    Q : int   Number of stator slots
    P : int   Number of poles
    m : int   Number of phases (default 3)

    Returns
    -------
    list[int]   Valid coil spans in ascending order (always non-empty).

    Examples
    --------
    >>> get_valid_coil_spans(12, 10)
    [1, 2]
    >>> get_valid_coil_spans(24, 4)
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    """
    valid = []
    max_span = Q // P or 1  # pole pitch floor; for FSCW this is 1
    # Also check spans up to electrical period for ISW
    p = P // 2
    elec_period = Q // p
    for w in range(1, max(max_span, elec_period) + 1):
        matrix = build_coil_matrix(Q, P, m, layers=2, w=w)
        counts = []
        for k in range(m):
            ph = k + 1
            cnt = (int((matrix[0] == +ph).sum()) + int((matrix[0] == -ph).sum()) +
                   int((matrix[1] == +ph).sum()) + int((matrix[1] == -ph).sum()))
            counts.append(cnt)
        if len(set(counts)) == 1:
            valid.append(w)

    return valid if valid else [1]

# %% ../../nbs/winding/03_sos.ipynb #d67000ff
def is_valid_combination(Q: int, P: int, m: int = 3) -> bool:
    """
    Return True if (Q, P, m) supports a balanced m-phase winding.

    A combination is valid when:
    - P is even and ≥ 2
    - Q and m have a common factor ≥ 1 (at least one slot per phase)
    - A double-layer coil matrix with the default span is balanced

    Parameters
    ----------
    Q : int   Number of stator slots
    P : int   Number of poles
    m : int   Number of phases (default 3)

    Returns
    -------
    bool

    Examples
    --------
    >>> is_valid_combination(12, 10)
    True
    >>> is_valid_combination(12, 10, m=5)
    False
    >>> is_valid_combination(7, 4)
    False
    """
    if P < 2 or P % 2 != 0:
        return False
    if Q < m:
        return False
    try:
        result = check_symmetry(Q, P, m, layers=1)
        return bool(result['valid'])
    except Exception:
        return False
