# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_winding_factors.ipynb.

# %% ../../nbs/01_winding_factors.ipynb #b777e8e5
from __future__ import annotations

import numpy as np

from .sos import build_coil_matrix, get_valid_coil_spans, winding_factor_sos

__all__ = [
    "pitch_factor",
    "distribution_factor",
    "winding_factor",
    "winding_factor_spectrum",
]

# %% auto #0
__all__ = ['pitch_factor', 'distribution_factor', 'winding_factor', 'winding_factor_spectrum']

# %% ../../nbs/01_winding_factors.ipynb #32c8de66
def pitch_factor(nu: int, coil_span: int, pole_pitch: float) -> float:
    """
    Pitch (chording) factor kp for the nu-th mechanical harmonic.

    kp(nu) = |sin(nu * pi/2 * w / tau_p)|

    Parameters
    ----------
    nu         : int    Harmonic order (1 = fundamental)
    coil_span  : int    Coil span in slots (w)
    pole_pitch : float  Pole pitch in slots (tau_p = Q/P, one magnetic pole)

    Returns
    -------
    float   kp in [0, 1]

    Examples
    --------
    >>> pitch_factor(1, 6, 6.0)   # full-pitch
    1.0
    >>> round(pitch_factor(1, 5, 6.0), 4)   # 5/6 chording
    0.9659
    """
    return float(np.abs(np.sin(nu * np.pi / 2 * coil_span / pole_pitch)))

# %% ../../nbs/01_winding_factors.ipynb #c8084474
def distribution_factor(nu: int, Q: int, p: int, m: int = 3) -> float:
    """
    Distribution (belt) factor kd for the nu-th harmonic.

    Valid for integer-slot windings (q >= 1).

    kd(nu) = sin(nu*pi/(2m)) / (q * sin(nu*pi/(2mq)))

    Parameters
    ----------
    nu : int   Harmonic order
    Q  : int   Total number of slots
    p  : int   Number of pole pairs
    m  : int   Number of phases (default 3)

    Returns
    -------
    float   kd in (0, 1]

    Raises
    ------
    ValueError
        If q < 1. Use winding_factor() for FSCW.

    Examples
    --------
    >>> round(distribution_factor(1, 12, 2), 4)   # q=1
    1.0
    >>> round(distribution_factor(1, 24, 2), 4)   # q=2
    0.9659
    """
    q = Q / (2 * m * p)
    if q < 1.0 - 1e-9:
        raise ValueError(
            f"distribution_factor() requires q >= 1 (integer-slot winding). "
            f"Got q = {q:.4f} (Q={Q}, p={p}, m={m}). "
            f"Use winding_factor() for FSCW."
        )
    num = np.sin(nu * np.pi / (2 * m))
    den = q * np.sin(nu * np.pi / (2 * m * q))
    if np.abs(den) < 1e-12:
        return 1.0
    return float(np.abs(num / den))

# %% ../../nbs/01_winding_factors.ipynb #029f0f98
def winding_factor(
    nu: int,
    Q: int,
    p: int,
    coil_span: int,
    m: int = 3,
) -> float:
    """
    Combined winding factor kw for harmonic nu.

    Dispatches automatically:
    - Integer-slot (q >= 1): kw = kp * kd
    - FSCW (q < 1): kw via star-of-slots phasor sum

    Parameters
    ----------
    nu        : int   Harmonic order (1 = fundamental)
    Q         : int   Total number of slots
    p         : int   Number of pole pairs
    coil_span : int   Coil span in slots.
                      Full-pitch for ISW = Q/P (one magnetic pole).
                      Tooth-coil for FSCW = 1.
    m         : int   Number of phases (default 3)

    Returns
    -------
    float   kw in [0, 1]

    Examples
    --------
    >>> winding_factor(1, 12, 2, coil_span=3)   # 12s/4p full-pitch (tau_p=3)
    1.0
    >>> round(winding_factor(5, 12, 5, coil_span=1), 4)   # 12s/10p FSCW working harmonic (nu=p=5)
    0.933
    >>> round(winding_factor(4, 12, 4, coil_span=1), 4)   # 12s/8p FSCW working harmonic (nu=p=4)
    0.866
    """
    P = 2 * p
    pole_pitch = Q / P
    q = Q / (2 * m * p)

    if q >= 1.0 - 1e-9:
        kp = pitch_factor(nu, coil_span, pole_pitch)
        kd = distribution_factor(nu, Q, p, m)
        return kp * kd
    else:
        return winding_factor_sos(nu, Q, P, m, layers=2, w=coil_span)

# %% ../../nbs/01_winding_factors.ipynb #65cdb654
def _optimal_coil_span(Q: int, P: int, m: int = 3, layers: int = 1) -> int:
    """
    Coil span (slots) that maximises kw at the working harmonic.

    Parameters
    ----------
    Q, P, m : int
    layers  : int

    Returns
    -------
    int

    Examples
    --------
    >>> _optimal_coil_span(12, 10)
    1
    >>> _optimal_coil_span(24, 4)
    6
    """
    p = P // 2
    q = Q / (2 * m * p)
    # For integer-slot windings, full pitch (Q//P) always maximises kp=1.
    # The SOS spectrum cannot distinguish spans in SL-ISW (only DL layers differ),
    # so we short-circuit here.
    if q >= 1.0 - 1e-9:
        return max(1, Q // P)
    spans = get_valid_coil_spans(Q, P)
    best_w, best_kw = spans[0], -1.0
    for span in spans:
        try:
            _, kw = winding_factor_spectrum(Q, P, m=m, layers=layers, w=span, nu_max=p)
            kw1 = float(kw[p - 1]) if p <= len(kw) else 0.0
            if kw1 > best_kw:
                best_kw, best_w = kw1, span
        except Exception:
            pass
    return best_w

# %% ../../nbs/01_winding_factors.ipynb #be73af1d
def winding_factor_spectrum(
    Q: int,
    P: int,
    m: int = 3,
    layers: int = 1,
    w: int | None = None,
    nu_max: int = 40,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Winding factor magnitude spectrum for mechanical harmonics 1...nu_max.

    Parameters
    ----------
    Q      : int   Number of stator slots
    P      : int   Number of poles (even, >= 2)
    m      : int   Number of phases (default 3)
    layers : int   1 (single-layer) or 2 (double-layer)
    w      : int | None
             Coil span in slots. None -> span that maximises kw.
    nu_max : int   Highest mechanical harmonic (default 40)

    Returns
    -------
    nu_arr : np.ndarray, shape (nu_max,), dtype int
    kw_arr : np.ndarray, shape (nu_max,), dtype float64
        |kw(nu)| in [0, 1]

    Examples
    --------
    >>> nu, kw = winding_factor_spectrum(12, 10, layers=2)
    >>> round(float(kw[4]), 4)   # nu=5 working harmonic for 12s/10p
    0.933
    >>> nu, kw = winding_factor_spectrum(12, 4, layers=1, w=6, nu_max=10)
    >>> round(float(kw[1]), 4)   # nu=2, 12s/4p q=1 full-pitch
    1.0
    """
    if w is None:
        w = _optimal_coil_span(Q, P, m, layers)

    matrix = build_coil_matrix(Q, P, m, layers, w)
    slots = np.arange(Q, dtype=np.float64)
    nu_arr = np.arange(1, nu_max + 1, dtype=int)
    kw_arr = np.zeros(len(nu_arr), dtype=np.float64)

    for idx, nu in enumerate(nu_arr):
        phasors = np.exp(1j * nu * 2.0 * np.pi * slots / Q)
        kw_vals = []
        for k in range(m):
            ph = k + 1
            total = 0j
            n_cond = 0
            for lyr in range(layers):
                fwd = matrix[lyr] == +ph
                ret = matrix[lyr] == -ph
                total += phasors[fwd].sum() - phasors[ret].sum()
                n_cond += int(fwd.sum()) + int(ret.sum())
            if n_cond > 0:
                kw_vals.append(abs(total) / n_cond)
        kw_arr[idx] = float(np.mean(kw_vals)) if kw_vals else 0.0

    return nu_arr, kw_arr
